---
- name: include vaulted passwords from vaulted.yml
  include_vars: vaulted.yml
- name: upgrade all packages
  become: yes
  yum:
    name: '*'
    state: latest
- name: enable the extended epel repo (for redis)
  become: yes
  command: yum-config-manager --enable epel
- name: install needed packages
  become: yes
  yum: "pkg={{ item }} state=latest"
  with_items:
    - git
    - gcc
    - make
    - python27-pip
    - redis
- name: create the environment variable file
  template:
    src: env.local.j2
    dest: ~/env.local
- name: clone public interface
  git:
    repo: https://github.com/ucldc/public_interface.git
    dest: "{{ codedir }}"
    update: yes
- name: install public interface dependencies
  become: yes
  pip:
    requirements: /home/ec2-user/code/public_interface/requirements.txt
- name: migrate db
  command: . ~/env.local; python manage.py migrate --noinput
  args:
    chdir: "{{ codedir }}"
- name: load content
  command: . ~/env.local; ./load-content.sh
  args:
    chdir: "{{ codedir }}"
- name: collect static files
  command: . ~/env.local; python manage.py collectstatic --noinput
  args:
    chdir: "{{ codedir }}"
- name: set "site"
  command: . ~/env.local; python manage.py loaddata fixtures/sites.json
  args:
    chdir: "{{ codedir }}"
- name: make sitemaps
  command: . ~/env.local; python manage.py calisphere_refresh_sitemaps
  args:
    chdir: "{{ codedir }}"

