---
- name: include vaulted passwords from vaulted.yml
  include_vars: vaulted.yml
- name: upgrade all packages
  yum:
    name: '*'
    state: latest
- name: install needed packages
  become: yes
  yum: "pkg={{ item }} state=latest"
  with_items:
    - git
    - gcc
    - make
    - python27-pip
- name: create the environment variable file
  template:
    src: env.local.j2
    dest: ~/env.local
- name: clone public interface
  git:
    repo: https://github.com/ucldc/public_interface.git
    dest: ~/code/public_interface
    update: yes
- name: install public interface dependencies
  pip:
    requirements: ~/code/public_interface/requirements.txt
